name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: ./gradlew packageExe
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'Sang-T MP (Windows)'
          path: 'D:\a\sang-t-mp\sang-t-mp\build\compose\binaries\main\exe\Sang-T MP.exe'
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: ./gradlew packageDmg
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'Sang-T MP (MacOS)'
          path: '/Users/runner/work/sang-t-mp/sang-t-mp/build/compose/binaries/main/dmg/Sang-T MP.dmg'