name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-windows-exe:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: ./gradlew packageExe
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'Sang-T MP (Windows.exe)'
          path: 'D:\a\sang-t-mp-project\sang-t-mp-project\app\build\compose\binaries\main\exe\Sang-T MP-1.0.0.exe'
  build-windows-msi:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: ./gradlew packageMsi
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'Sang-T MP (Windows.msi)'
          path: 'D:\a\sang-t-mp-project\sang-t-mp-project\app\build\compose\binaries\main\msi\Sang-T MP-1.0.0.msi'
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: ./gradlew packageDmg
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'Sang-T MP (MacOS)'
          path: '/Users/runner/work/sang-t-mp-project/sang-t-mp-project/app/build/compose/binaries/main/dmg/Sang-T MP-1.0.0.dmg'