name: Windows build

on:
  push:
    branches: [ windows ]

jobs:
  build-windows-msi:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '16'
      - run: ./gradlew packageMsi
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'Sang-T MP (Windows.msi)'
          path: 'D:\a\sang-t-mp-project\sang-t-mp-project\app\build\compose\binaries\main\msi\Sang-T MP-1.0.0.msi'